global:
    type: OPENFALCON
    flush_period: 10

services:
    kafka:
        host:
            - c1-app7
            - c1-app8
            - c1-app9
        jmx_port: 9999
        thread_num: 1
        items:
            gauges:
                Message_in_rate:  'kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec'
                Byte_in_rate: 'kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec'
                Byte_out_rate: 'kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec'
                Leader_election_rate: 'kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs'
                Unclean_leader_election_rate: 'kafka.controller:type=ControllerStats,name=UncleanLeaderElectionsPerSec'
                Partition_counts: 'kafka.server:type=ReplicaManager,name=PartitionCount'
                Leader_replica_counts: 'kafka.server:type=ReplicaManager,name=LeaderCount'




